# Generated by Django 5.1.3 on 2024-11-26 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageEncoding',
        ),
    ]
