# Generated by Django 5.1.3 on 2024-11-25 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_rename_username_user_name_user_last_login_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
