# Generated by Django 5.1.3 on 2025-02-01 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_signup_role_alter_signup_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='country',
            field=models.CharField(choices=[('EG', 'Egypt'), ('US', 'United States'), ('UK', 'United Kingdom'), ('IN', 'India'), ('FR', 'France')], default='EG', max_length=50),
        ),
        migrations.AddField(
            model_name='signup',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
