# Generated by Django 5.1.3 on 2025-02-01 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_signup_is_verified_signup_token_expiry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='token_expiry',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='verification_token',
        ),
    ]
