# Generated by Django 5.1.3 on 2025-02-01 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_remove_signup_is_verified_remove_signup_token_expiry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='signup',
            name='token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='verification_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
