# Generated by Django 5.1.3 on 2025-02-02 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_alter_signup_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
